### PR TITLE
a typo in  utils-set-operations.R

### PR DESCRIPTION
**Pull request by jlacko**
intersect for intersection, setdiff for difference

### CODE REVIEW

**Comment by JosiahParry** [comment]
@jlacko thank you!!!!

**Comment by jlacko** [comment]
Glad to be of service! and just for the fun of it - imagine for a moment my surprised face when I read the man page as it stood :) Of course then I checked the raw code & knew what needed to be done. But the short moment of utter disbelief - priceless...

**Comment by JosiahParry** [comment]
I'm glad it can be of use! 
I use these set functions all the time for making custom neighborhoods--e.g contiguity but making sure there are at least 4 neighbors or something. 

I'm no longer able to maintain this package so any and all PRs are super very much appreciated

**Comment by jlacko** [comment]
It definitely is of use! I tweak my weights all the time - and your functions are super helpful in that. Thanks for sharing!

**Pull request merged**
